// ********** AUTH **********
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const INITIAL = 'INITIAL';
export const INITIALIZE_SESSION_AND_SOCKET = 'INITIALIZE_SESSION_AND_SOCKET';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

// ********** STUDENT **********
export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_BY_ID_REQUEST = 'GET_STUDENT_BY_ID_REQUEST';
export const GET_STUDENT_BY_ID_SUCCESS = 'GET_STUDENT_BY_ID_SUCCESS';
export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const CLEAR_STUDENT = 'CLEAR_STUDENT';
export const CLEAR_STUDENT_LIST = 'CLEAR_STUDENT_LIST';
export const CLEAR_TOTAL_STUDENTS = 'CLEAR_TOTAL_STUDENTS';
export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const STUDENT_ERROR = 'STUDENT_ERROR';
export const ASSIGN_COURSE_STUDENT_REQUEST = 'ASSIGN_COURSE_STUDENT_REQUEST';
export const ASSIGN_COURSE_STUDENT_SUCCESS = 'ASSIGN_COURSE_STUDENT_SUCCESS';
export const GET_ASSIGNED_COURSES_REQUEST = 'GET_ASSIGNED_COURSES_REQUEST';
export const GET_ASSIGNED_COURSES_SUCCESS = 'GET_ASSIGNED_COURSES_SUCCESS';
export const DELETE_ASSIGNED_COURSE_REQUEST = 'DELETE_ASSIGNED_COURSE_REQUEST';
export const DELETE_ASSIGNED_COURSE_SUCCESS = 'DELETE_ASSIGNED_COURSE_SUCCESS';

// ********** COURSE **********
export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_BY_ID_REQUEST = 'GET_COURSE_BY_ID_REQUEST';
export const GET_COURSE_BY_ID_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CLEAR_COURSE = 'CLEAR_COURSE';
export const CLEAR_COURSE_LIST = 'CLEAR_COURSE_LIST';
export const CLEAR_TOTAL_COURSES = 'CLEAR_TOTAL_COURSES';
export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const GET_ASSIGNED_STUDENTS_REQUEST = 'GET_ASSIGNED_STUDENTS_REQUEST';
export const GET_ASSIGNED_STUDENTS_SUCCESS = 'GET_ASSIGNED_STUDENTS_SUCCESS';
export const DELETE_ASSIGNED_STUDENT_REQUEST = 'DELETE_ASSIGNED_STUDENT_REQUEST';
export const DELETE_ASSIGNED_STUDENT_SUCCESS = 'DELETE_ASSIGNED_STUDENT_SUCCESS';
export const COURSE_ERROR = 'COURSE_ERROR';

// ********** ERROR & MESSAGE **********
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
